In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
files.upload()

Saving Análisis_de_Piso.xlsx to Análisis_de_Piso.xlsx

{'Análisis_de_Piso.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x9e,lok\x01\x00\x00\x10\x05\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x94\xc1N\xc30\x0c\x86\xefH\xbcC\x95+j\xb3q@\x08\xad\xdba\xc0\x11&1\x1e $\xee\x1a-M\xa28\x1b\xdb\xdb\xe3fcB\xa8\xacB\xeb\xa5Q\x1b\xfb\xff\xbf\xb8v&\xb3]c\xb2-\x04\xd4\xce\x96l\\\x8cX\x06V:\xa5\xed\xaad\xef\xcb\xe7\xfc\x9ee\x18\x85U\xc28\x0b%\xdb\x03\xb2\xd9\xf4\xfaj\xb2\xdc{\xc0\x8c\xb2-\x96\xac\x8e\xd1?p\x8e\xb2\x86F`\xe1<X\xda\xa9\\hD\xa4\xd7\xb0\xe2^\xc8\xb5X\x01\xbf\x1d\x8d\xee\xb8t6\x82\x8dyl5\xd8t\xf2\x08\x95\xd8\x98\x98=\xed\xe8\xf3\x81$\x80A\x96\xcd\x0f\x81\xadW\xc9\x84\xf7FK\x11\x89\x94o\xad\xfa\xe5\x92\x1f\x1d\n\xcaL1Xk\x8f7\x84\xc1x\xa7C\xbb\xf3\xb7\xc11\xef\x95J\x13\xb4\x82l!B|\x11\ra\xf0\x9d\xe1\x9f.\xac?\x9c[\x17\xe7E:(]Ui\t\xca\xc9MC\x15(\xd0\x07\x10\nk\x80\xd8\x98"\xadE#\xb4\xfd\xe6>\xe3\x9f\x82\x91\xa7e<0H{\xbe$\xdc\xc3\x11\xe9\x7f\x03O\xcf\xcb\x11\x92L\x8f!\xc6\xbd\x01\x1c\xba\xecI\xb4\xcf\xb9\x16\x01\xd4[\x0c4\x19\x83\x03\xfc\xd4\xee\xe1\x90\xc2\xc8yM-2p\x11N\xba\xe7\xfc\xa9o\x17\xc1y\xa4\t\x0e\xf0\x7f\x80\xef\x11m\xb3sOB\x10\xa2\x86\xd3\x90v5\xfb\xc9\x91\xa6\xff\xe2\x13C{\xbf(P\x1d\xde<\xddg\xd3/\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xb5U0#\xf4\x00\x00\x00L\x02\x00\x00\x0b\x00\x08\x02_rels/.rels \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92MO\xc30\x0c\x86\xefH\xfc\x87\xc8\xf7\xd5\xdd\x90\x10BKwAH\xbb!T~\x80I\xdc\x0f\xb5\x8d\xa3$\x1b\xdd\xbf\'\x1c\x10T\x1a\x83\x03G\x7f\xbd~\xfc\xca\xdb\xdd<\x8d\xea\xc8!\xf6\xe24\xac\x8b\x12\x14;#\xb6w\xad\x86\x97\xfaqu\x07*&r\x96Fq\xac\xe1\xc4\x11v\xd5\xf5\xd5\xf6\x99GJy(v\xbd\x8f*\xab\xb8\xa8\xa1K\xc9\xdf#F\xd3\xf1D\xb1\x10\xcf.W\x1a\t\x13\xa5\x1c\x86\x16=\x99\x81Z\xc6MY\xdeb\xf8\xae\x01\xd5BS\xed\xad\x86\xb0\xb77\xa0\xea\x93\xcf\x9b\x7f\xd7\x96\xa6\xe9\r?\x889L\xec\xd2\x99\x15\xc8sbg\xd9\xae|\xc8l!\xf5\xf9\x1aUSh9i\xb0b\x9er:"y_dl\xc0\xf3D\x9b\xbf\x13\xfd|-N\x9c\xc8R"4\x12\xf82\xcfG\xc7%\xa0\xf5\x7fZ\xb44\xf1\xcb\x9dy\xc47\t\xc3\xab\xc8\xf0\xc9\x82\x8b\x1f\xa8\xde\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x000\x9d\x8dt\xc6\x03\x00\x00+\t\x00\x00\x0f\x00\x00\x00xl/workbook.xml\xacU\xe1n\xdb6\x10\xfe?`\xef@\xe8\xbf"R\x96dI\x88SX\x96\x84\x06\x88\xdb\xc0q\x93\r0\x100\x12\x1ds\x91D\x8f\xa4cgA\x1fiO\xd1\x17\xebQ\xb6\x9c\xa4\x1e\x06/]\xe0\x90"y\xfc\xf8\xdd\xddw\xe4\xe9\x87M]\xa1G&\x15\x17\xcd\xc0"\'\xd8B\xac)D\xc9\x9b\xfb\x81\xf5e\x9a\xdb\xa1\x85\x94\xa6MI+\xd1\xb0\x81\xf5\xc4\x94\xf5\xe1\xec\xd7_N\xd7B>\xdc\t\xf1\x80\x00\xa0Q\x03k\xa1\xf52v\x1cU,XM\xd5\x89X\xb2\x06V\xe6B\xd6T\xc3P\xde;j)\x19-\xd5\x821]W\x8e\x8bq\xe0\xd4\x947\xd6\x16!\x96\xc7`\x88\xf9\x9c\x17,\x15\xc5\xaaf\x8d\xde\x82HVQ\r\xf4\xd5\x82/U\x87V\x17\xc7\xc0\xd5T>\xac\x96v!\xea%@\xdc\xf1\x8a\xeb\xa7\x16\xd4Bu\x11\x9f\xdf7B\xd2\xbb\n\xdc\xde\x10\x1fm$\xfc\x02\xf8\'\x18\x1a\xb7;\t\x96\x0e\x8e\xaay!\x85\x12s}\x02\xd0\xce\x96\xf4\x81\xff\x04;\x84\xbc\t\xc1\xe60\x06\xc7!y\x8ed\x8f\xdc\xe4p\xcfJ\x06\xefd\x15\xec\xb1\x82\x170\x82\x7f\x1a\x8d\x80\xb4Z\xad\xc4\x10\xbcw\xa2\xf9{n\xaeuv:\xe7\x15\xbb\xdeJ\x17\xd1\xe5\xf2\x13\xadM\xa6*\x0bUT\xe9\xac\xe4\x9a\x95\x03\xab\x0fC\xb1fo&\xe4j\x99\xacx\x05\xabn@z\xd8r\xce\xf6r\xbe\x94\xa8ds\xba\xaa\xf4\x14\x84\xdc\xc1Ce\x04A\xe4\xfa\xc6\x12\x841\xac4\x93\r\xd5l$\x1a\r:\xdc\xf9\xf5\xb3\x9ak\xb1G\x0b\x01\nG\x13\xf6\xe7\x8aK\x06\x85\x05\xfa\x02_\xa1\xa5EL\xef\xd4%\xd5\x0b\xb4\x92\xd5\xc0\x1a\xc5\xb3/\n\xdc\x9f\xd1j.\xd9\xecs\xc3R\xc9\x1f\xd9\xac\xab\x0e\xa1fSV\x80;hlhJ\xc9\x9ef.v\x03t\x05\x8e)-\x19Jn\xa7L\x16\\\xa0[2\xbb\x84"\xa2m\xb9*\xb3\x856\xb4\xfa\xf6\xb7\xe6\x055\xa3\x86\xdd\x0b\xb0ShI%EP\xcc\xb4\xe1\x7fQ\x98i\x98\x9a\xbd*\x04zXu\xff\xa1\x14ha\xe2\xeb@\x80\xb7A\xd8~\xff\x18l\x88\x85\x8c;\xb9_j\x89\xe0\xfb<\xbd\x80\x94_\xd1G\x10\x00\xc8\xac\xdc\xdd\x0f\xe7\x90\xe1\xf0\xf69\'\x19\xee\x87\xaek\x87~\x9e\xdb^\x98\x84v\x94\x06\xd8\x0eI\x14%Y\x7f\xd8#a\xfe\x15\xbc\x90A\\\x08\xba\xd2\x8b\x9d\xa8\x0c\xe6\xc0\xf2@A\x07Kc\xba\xe9V\x08\x8eW\xbc|9\xff\x19\xef\xfel\xd3\xff\xd0tk_\x8d\xa7\xe6\xfa\xbc\xe6l\xad^\xe4g\x86hs\xc3\x9bR\xac\x07\x96M\\\xf0\xe6\xe9\xedp\xdd.\xde\xf0R/@\xbf\xb8\x0f\xfaE\xdb\xb9\x8f\x8c\xdf/\x801!\xd83\xc5&]\xc3l`=G\xa9\xeb\xa7\x1e\xf6\xec\xe10Im/\xc0\x89\x9d\xf4\xd3\xc0v]L\xf2l\x18\xb9\xf9\xa8\xd72r^Qj/j\xa0\xd6\xf6\xa8i\x8b\xeb\xa3\xf8\x83\x12x\x10\xcc\x1dn\x82\x0b\xdf26G\xc8\xf3\x92\xb4\xc9\xebv\x15\xb4*\xa0\x96L\xd7\x1aF\x04\xbb\x91\xb1`\x1b}\xa1t\xdb\x83\x8c9\xb0#\x1e\x1e\xf6q\xe4\xd98\xeb\xf9\x90\x9e\x08\x12\xe5\xf5\\{\xe4\xa5n\xe6\xf7\xb34K|\x93\x1e\xf3\xce\xc4\xff\xc7m\xdbVS\xdc=`\x86\xe5\x82J=\x95\xb4x\x80go\xc2\xe6\tU \xa4\xadC\xc0\xf75\xd9\xc4\x0f\x13\xdc\x03\x8a^N@K$\xc2v\x92\x04\x9e\xed\xa7y\xcf\xef\x93t\x94\xf9\xad\x96\xb6d\x8d\xfb\xf3w\xdeu\xa1\xd3\xeefT\xaf\xe0\x1e0W@;\x8eM\x9b\xeff\xf7\x93\xf3\xed\xc4.Moj.\x9e\xa4&\xee\xbb\xdd\xfffx\x05\xdeW\xecH\xe3\xfc\xfaH\xc3\xd1\xa7\xf1t|\xa4\xedE6\xbd\xbd\xc9\x8f5\x1e\x8e\x93tx\xbc\xfdp2\x19\xfe>\xcd~\xeb\x8ep\xfe1\xa0N\x9bp\xd3\xb62u:\x99\x9c}\x07\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x92\x07\x94\xec\x04\x01\x00\x00?\x03\x00\x00\x1a\x00\x08\x01xl/_rels/workbook.xml.rels \xa2\x04\x01(\xa0\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92\xcbj\xc40\x0cE\xf7\x85\xfe\x83\xd1\xbeq2}P\x86qf\xd1R\x98m\x9b~\x80p\x948Lb\x07[}\xe4\xefkR:\xc9\xc0\x90n\xb21H\xc2\xf7\x1e\x89\xbb\xdb\x7fw\xad\xf8$\x1f\x1ag\x15dI\n\x82\xacveck\x05\xef\xc5\xcb\xcd#\x88\xc0hKl\x9d%\x05\x03\x05\xd8\xe7\xd7W\xbbWj\x91\xe3\xa7`\x9a>\x88\xa8b\x83\x02\xc3\xdco\xa5\x0c\xdaP\x87!q=\xd98\xa9\x9c\xef\x90c\xe9k\xd9\xa3>bMr\x93\xa6\x0f\xd2\xcf5 ?\xd3\x14\x87R\x81?\x94\xb7 \x8a\xa1\x8f\xce\xffk\xbb\xaaj4=;\xfd\xd1\x91\xe5\x0b\x162\xf0\xd0\xc6\x05D\x81\xbe&V\xf0[\'\x91\x11\xe4e\xfb\xcd\x9a\xf6\x1c\xcfB\x93\xfbX\xca\xf1\xcd\x96\x18\xb25\x19\xbe\x9c?\x06C\xc4\x13\xc7\xa9\x15\xe48Y\x84\xb9_\x13Fc\xab\x9f\x0c6v\x829\xb5\x96.r\xb7j(\x0cz*\xdf\xd8\xc7\xcc\xcf\xb31o\xff\xc1\xc8\xb3\xd8\xe7?\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xc5\x85\xe3\xc8\x1d&\x00\x00Q\xe7\x00\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\x9c\x93K\x8f\x9b0\x14\x85\xf7\x95\xfa\x1f\x90\xf7\xc4<\xa7\x13\x04\x19E!\xa8\xb3\xab\xfa\x1aui\xcc%X\xc16\xb5\x9dI\xa2\xaa\xff\xbd\x17\xa2$\xd5d\x13\x8d\x04\x92\xb9\xb6\xbfs\x8f}\xc8\x9f\x0e\xb2\xf7^\xc1X\xa1UA\xc2Y@<P\\7Bm\n\xf2\xe3{\xe5?\x12\xcf:\xa6\x1a\xd6k\x05\x059\x82%O\x8b\x8f\x1f\xf2\xbd6[\xdb\x018\x0f\t\xca\x16\xa4sn\xc8(\xb5\xbc\x03\xc9\xecL\x0f\xa0p\xa6\xd5F2\x87\x9ffC\xed`\x805\xd3&\xd9\xd3(\x08\x1e\xa8dB\x91\x13!3\xf70t\xdb\n\x0e\xa5\xe6;\t\xca\x9d \x06z\xe6\xb0\x7f\xdb\x89\xc1\x9ei\x92\xdf\x83\x93\xcclw\x83\xcf\xb5\x1c\x10Q\x8b^\xb8\xe3\x04%\x9e\xe4\xd9\xf3Fi\xc3\xea\x1e}\x1f\xc2\x84q\xef`\xf0\x89\xf0\x8d\xcf2S\xfdFI\nn\xb4\xd5\xad\x9b!\x99\x9ez\xbe\xb5?\xa7s\xca\xf8\x85t\xeb\xff.L\x98P\x03\xafb\xbc\xc0+*z_KazaEWX\xfcN\xd8\xc3\x056\x1e\x97\xc9v\xa2)\xc8\x9f8\x88\xca0\xa8"\xff1J\x97~R\x06\x95?\x8f\xd7\x89\xbf\xfaT\xad\xe22]\x07\xebU\xfa\x97,\xf2F\xe0\r\x8f\xae<\x03mA\x96a\xb6\xfc\x95\xc4\x84.\xf2)A?\x05\xec\xed\x7fc\xcf\xb1\xfa\x1b\xf4\xc0\x1d\xa0JH\xbc1\xa0\xb5\xd6\xdbq\xe13\x96\x02d\xdai\xc1\xc8\xb4\xbf\xdfR\xe9\x05\xbb\xc8\xaf\xe3\xb3D5\xe5\xf8\x8b\xf1jfa\xa5\xfb\x17\xd1\xb8\x0eu\xf0\x7fi\xa0e\xbb\xde}\xd5\xfb\xcf 6\x9d\xc3j\x8a~\xc7\xc0d\xcd\xb1\x04\xcb1\xa9\xa8?\x8bR\xec\xfe\x1f\x00\x00\x00\xff\xff\x00\x00\x00\xff\xff\xa4\x9dYo$Gv\x85\xff\xcaX~\xb1_\xbaY$\x9b\xdd\x1cH\rd\xed\xfb^\xac\xe5M\x905\x90a`\xc6\xb0\x04\xd9\xfe\xf7\x8e\xac\x8a\xed\x9e/3\xc8\x82\x1b\x18Ps\xee\x8d\xc8\xc8\x88\x93\'o,7\xeb\xc7\xdf\x7f\xfb\xf5\xd7?\xfa?\xff\xf1\xf3\xf7\x1f\xff\xeb\x1f\xff\xfd\x97\xff\xfa\xe9\x87\xce\x0f\x7f\xf9\xfd?\x7f\xfe\xfb\xef\xee\xbf\xfe\xfa\xc5\xfd\x9f\xdf\xfe\xf8\xe9\x87\xa7/\x9f\x1e\xbf\xfc\xf0\x97?~\xfb\xf7_\xfe\xa3\xfb\x0f\x078\xfc\x7f:\xcf?\xff\xf2\xd7\x7f\xfb\xdf\xfe\xaf\xbf\xff\xf2\xeb\xdf\x1d\xf6\xf0\xe9\xe9\x87\xef?\xfeR\xd7Q\xd5\x95\xd4^\x9f=\xd0\xbd\x01\x8f\xae\x8e\x9f~\xf8\xdd\xb9\xfd\xf9\xfd\xe1\xc7\xcf\x7f~\xff\xf1\xf3/\xde\xa3\x17<B\x91\xbe\x02\x03\x05\x86\n\x8c\x14\x18+0Q`\xaa\xc0L\x81\xb9\x02\x8b\x1b\xf0\x94\xddK\xc7\xde\xcb2x\x84{Y)\xb0V`s\x03\x9e\xb3J\x1fm\xa5\xdb\x9bG=\x0c\xa1\x0b\x9f\xac\xc7\xee\xe6\xf1\x92y<[\x8f\xfd\xcd\xe3k\xe6\xf1\xc5z\x1cn\x1e\xdf2\x8f\x17\xeb\xf1\x16<\xc2\xcd\x1d\x158)pV\xe0\xa2@\xe5\x19\xf3-2\xa6\xf2\x94\xc9\x10O\x91\x0c\xf1\x1c\xc9\x10O\x92\x0c\xf1,\xc9\x10O\x93\xd7\xec\x1e\xbf\xda{\xac<q^Ss<s2\xc4S\xa7\xf3\x90\x9c<y:\xee\xf6\xe2 }\x93\xaa=\x9f:\x8f\xa9\x98gT\x0ey\n\xa5\'\xa8\xf2\x1c\xea\\\x1f\x9e\xc7\x17\x19\xfb\xca3*+\xe0)\x95!\x9eB\x9d\xfa9\xfd\xf3\xfb\xeb\xd7Wi\x9a\'\x90\xb7\x7f\xeb\x08\xad+O\x9f\xacFO\x97\x0c\xf1\xf4p\xf7\x92\xba@\xaf\xe3\x19S\xf4\xf1$\xcaj\xf6,\xba"\x9f\x9dXE\xc5r\x97\x82bu\xbe|\xfaz\x97b\xd5\x95\x18\xc5\xf2\xc0\xf3\xb5\xaf\x9e\xbf\xc8=\xf4\xbc\xf9\xcbm8\x84?}c}\x95gl`\xac\x9d\x8e(\xe1\xd0\x98_\xa4\xf0\xc8\x16~\x90+\x8f\x8d\xf9\x9b\x90ob\xaczOSc}\x96f\xcdlY\xe1\xdf\xdc6ZZ\xb50\xd6\xaf*\x97\xb6\xacXW\xf6\x8e\xa4Uko}\xb9\x8e\xc3\x93t\xd6\xc6X;\xcf\x1di\xd7\xd6\xd8_^\xe4\xd2;o~\x8a\x8f\xea\x1e\xc8\xc1#_o\xcf\x94h\xa57~\xbb\x1a\xa5qGc\x14~\x9d\x8cQ\xdau6F\x19\x89\x8b-)\xfdUU\xa5\xabV]c\x15\xe5\xaf\x02\xe9o\xb7\xa3\n\x14H\x7f\xb3B<\x02\xebofU\xc5@z_X[\x1dX\xef\xcd\xf2j\xac\x02\xebof\x95\x9b\xc0\xfa\x9b\xec\xc9+\xb1\n\xac\x7fuc\xf4\xb7\xef\xbb\xc3\xe2_\xaa\xe9\xf3_\xdd\xff\x9e\xfe\xf5\xc7\xcf\x7f\xab\x85\xb2\xa3\x97\xf3\x8f\xc2\xe3C*2sEf\xa9\x88\xf6\x8d\x7f<\x1e\xf3\x17\x83>\xf7\x95\x7fJ\xac\x93j\xf0\xf26B\x8f\xeeO|\xc5\xa0\x81\xfe\x99y41\n\xde\x18\xbe\xa6<\xe6\xe8h\xef\xf8\'\xe8\x1a\xfd\x85\xb0\xa3#D\xae\xfccd\x9d\x94<\xfea\xb2N\xfa\xde\xf5\xcf\x97uR\xae\xf8G\xce:\xe9\xa0\xbf\xf9\xbb\xcb\xe3\xa5G\xa5\x95\x7f\x04MM\x8f\xda\xe3\xfeQ|\xcc\xe3\xaaG\xa5\x84\x7f$\xadS\xeaq\xf3\xber\xa3\xf2\xff\x7f_\xd5\x95\xfc\xf4\xc3c\x1e\xca=\xca\xe0u\xbdO\x1e\xcc=\xca\xd8\xf5\xbcO\x1e\x0c=\xca\xd0\xf5\x9b|d\xe4\x06M>2p\xc3&\x1f\x19\xb7Q\x83\xcf\x93\x0c\xdb\xb8\xc9GFm\xd2\xe4#\x836m\xf2\x91\xa7d\xd6\xe4#\xfd<o\xf2\x91~^4\xf9H?/\x9b\xfaG\xeaY}`\xbc\xd6\x1f\x18\xafMS{\xf4\xed\xf8\x01\x9f\xdd\xcd\'\x85i{\x05\x0e\xbe\x96\x12\x0b\xdf>pW\xc7\x0f\xdc\xd5\xa9\xc9GXxn\xf2\x11\x16^\x9a\xee\x1co\xd2&\'\x15\x8f\xf0\x0c\xe6\xcf\xd7\x93\x8aG\xd3C\xf8\x84\xd7k\xd3\xe5T\xae\x9b\x1eC\r\x8a\xaa\xa6\xe7\xf0I\xe5\xda?\x88O\x0f\xf9\x8cT\x85\xdf?\x89O\xf9kM\xd5\xa3\xf2\x8f\xe2S\xfe\xc6zT\xe1\xf7\xcf\xa2\xa9\xe9I\x85\xdf?\x8cO\xae\'\xd2\x1cX\x85?<\x8d\xd9\xcc!<|\x19\x14\x9e\xb5l\x16\x16\x1e\xad\x14\xedU\xfeIzzNs\xb5\xf0\xe0|I\xd0\xd6\x8fL\x06\xf9\xc7\xc2\xbdX\xc2,\xb9\xf2\x0fF\x0e\x85G#\xf3\nOB\x06\x05\xe2gP\xe0\xf9K\xaa>\xd0\xfa\n\x99\xd7\x8d{\xbf\x9b\xd7M\xc3\xc2\x8dkTX\xb9\xa9\xbd\xaf\xeb;\xb1\x87u"\xd0\r.ul\xf4(4\xed\x05c\\\xc6Q`\xa0\xc0P\x81\x91\x02c\x05&\nL\x15\x98)0W`\xa1\xc0R\x81\x95\x02k\x056\xa5\xae\xd8\xe6F\x11\x8f]n\xd3Y\xc9\xde\xd4*\x0f\xc1\xe1f|2\xeb@\xf24\xbdi;\x8f\n\x9c\x148+pQ\xa0\xaa\x80D&D\x92c\xf8\xab>J\x81\x00\x15\x18P\x81\x02\x158PE\x12db\x00Y\xc1\xd5=1\x9e\xb2G\'R\xa3aY\xb2\x8a4i2z\xca<\xdd&\x7f\xfa\x82\x88\xfc\xb9N"d\xad%r\xa9\xe9)\xaa<\xb1Z*6\xcc\xd27\x8e\xa1\x96\n\xb6\xa7\x96\xafW\x8b\x06n\xdd\xa6Qz;\x91U\xa9\xbf\x9f\xb5\x86H\xb4\xccG\xdfv\x91{M\xdd\x12yx\xed\x96\xd4\x04\xa3h\x8e\xfbw(Z\xed-\x8a&\xa2\xd5\r.\r-\xea\x05[\x144\x05\x06\n\x0c\x15\x18)0V`\xd2\xd0Hy\xb7O\xb5\xcc\xac\xd0\xeayn\x937\xe4\xc2\x94\x13\x86,\x8dQ\x86ne\x8cR\xed:7\xea:Ln{\xd1\x85mc\xd4%\x98\xdc(R\xb8\xbf\xd9\x9e\xea\x99\xfb\x9f\xdfeL\x0f\xde\xe8\xfe\xa4XAuR\xbb\xf4\xa8\xc0I\x81\xb3\x02\x17\x05\xaa\nH\xe4W\xd2I\xf8\xf4M\xdf\x8aXD\x8a]\x9f\n1F\xba\xd5F\r\x08#\xf5\x9a\x1e\xb6H\xc3\xa6j#%\x9bJF26\x19=1\x8d\xc4\x9a\xbbSe\xb1\x8c\xc4\x8a\x87\x1fI/\xb2\x9f:\x1a\x16ZZ\xaa\xd5\xf0R\xa3\xdc\x8d\xd4\xad+\x80\xd56o\xb8.\x98V\xbb\xdc\xaaqR\x15\xf8\x19\x1a\xfe\x04\xbd\xf5W\xf7z\xfb\xe9A\xa5\xf2-\xd4\x9f\xc9\xa9Jz\xe4l\xe6\xa3\xb7\x19i\\\x0f\x97\xbe##\xa5\xafc\xd9"\xb9n\xf1\xe3\x0e\xc9\xad\xbdEr\xe5\xaa\xdd\xe0\x12\x1e\x89\x9e\x02\xfd\x004Pl\xa0\xceC\x05F\n\x8c\x15\x98(0U`\xa6\xc0\\\x81\x85\x02K\x05V\n\xac\x15\xd8\x14\xees\x9b\xdb4\x84\xccm:U\xda\xe7\xc6G\r!o\xc6r\x08\xa9\xcd<*pR\xe0\xac\xc0E\x81\xaa\x02\x02\x1eT B\x15\x99\x10\xe5\x13\xe3_\x81\x00\x15\x18P\x81\x02U\xe4@)\x84D\x9b=/\x8c\xbe\x15\x06\xaa\x8a,i\x0c!\xfd`\xb4\x84\x90\xb8x\xe4OSe\x9eKmac\x81i\xd5\xaed\xf4tj\xa9\xf7\xe0o\xa1%l\x0c\x15g\xfa\xa4\x1a\x1d\xc9U\xf0\x01\xdf\xaa\x9cp&>t\x8b\xa2w\x88U\xed-b%\xa1M7\xb8D\xb1R\xa0\xaf\xc0@\x81\xa1\x02#\x05\xc6\nL\x02\xd0\xa0\x80\xd3\xdc&r?\xd3\x8a\xe6\n,\x14X*\xb0\xca\xeb\xd7u\xf3u\xe1\xe2\x9b\xdc\xa6\x8bX\xdb\x92qgnWO.\xe4F\xd5\xb3\x9b\xad\xacgz\x83G\x05N\n\x9c\x15\xb8(PU@@\x95\xaagzRb7\xf0\xa6\x02q*0\xa7\x02u\xaa\xc8\x9d\xa6x,\xf2\xa8\xa4rfd\xa4\x95\x9ePN\xf0\x9a\x02\xc5\xc8\xae\xda\xa8OvdZC\x88^y\xd6\x05Y\xf9\xf4\xa0ky\x86\x85\x08\xec\x0c_4\xb6\xf2<\x8cuc1\xd1pQ_\x91\x95!#\x02\xb7\xbdg\\\x88\xec\x1e\xbf\xbd\x9a\x7f\xd8\xb1\xf2\xfe1\xd0\xd3\xd6\xbe\x85{IC\xf4\x05\x9bU\r>\xd8\xab\xca\xfbD{3\x12\xfaJ\x92\xd4F\xa3\x9dn\x99\xfe\x0e\xed\xac\xbd\xadv~\x91\x18\xb6\x1b\\\xa2v*\xd0W`\x10\x80\x06\xb6\r\xd5y\xa4\xc0\xb8Pz\x92\xdbd\x90\xa6\xb9M\xd4g\x96\xdbt\xdfvn\x8c2"\x8b\xdc(1\xf0\xd2\x14\x94\xf9\xebJ\xefk\xad\xc0&/\xfeE\xf7n\x8cQ\xe6\x0c\xbb\xdc(,\xd9\xdfl\xcf\xf5\xde\xf6\x9f\xdf\xf5t\xd8\xcdXVZm\xe7Q\x81\x93\x02g\x05.\nT\x15\x90H\xac&M\xea\xc1=\xb2\xacI\x88\x0c\xe3\xf4\x99\x02\xe5\xaa\xc8\xb9\xa6\xba"\xffb\xb4\x1aYW\xd2_4\xd8s\xceD\x99\xf9\xb8\xe94\xce0M\x1f}O\xb5\xa8\x86\x1d\x9d!F\xba]\xb5A\xe7\x98\x91{M\x12\xefy\x18\xeb\xd6\xaa\xb7y\xab_t\x81\xc2pQwz+\xcf\xc6X\xb7n7T\x07\xcf\xc8\xf6)t\xb8z\xa6\xac\xba\xb5\x16\x19\x9a\xf9h;#i\xaf\x1d\xa45D\x06\xd7\xd642FY\xdd\x16\xe0\x1d\xcaZ{\x8b\xb2\xca\xa8t\x83KTV\x05\xfa\n\x0c\x14\x18*0R`\xac\xc0D\x81i\x00\x1ab\x8fY\xc16\xd7\x8a\x16\x05\xe7e\xc1\xb6\xd2\x8a\xd6\nl\xf2\xd22\xb2\xdb\x82m\x97\xdbt\xdbvo\x9a$\x8f\xe3\xe1f,+\xa56\xf3\xa8\xc0I\x81\xb3\x02\x17\x05\xaa\n\x08\x88R\xf5\xe0\x03\xaaT\xe0J\x05\xb2T\x91-Ma\'\x98SE\xea\x94\x84\x10M\xf3\x1c2BX`CU\xa2Q\xe5y\x94\x04E\xa5.\x92\xa9\xbe%\x15\x81H\xac\xeb\xfd\xaa\x02{\x96\xb5\xd7m\xa8\x86sF\x86l\xd8E\xf7lK\n\xae\x12\x1f\x18\xd7\x1ec\x86N\xcbTN\xb5:20\xf3\xd1\xdb\x8c\xa4\x940\xf2v\xf2?2\xf4\xfaZn9\x01\xe5\xceL\xdf\xa3\x85Ww\x11C\x89\xde\xba\xd1\xa7\xa9U=k\x95\xc8\xbao\xacz4a`\xacOB\x89\xa1\xadYb\x87\x91-k\xa7U\xe3h\x0c\x02>\x012\x052\x032\x07\xb2\x00\xb2\x04\xb2\x02\xb2\x06\xb2\x91n\x93\xb7\xde\xb6tw;ol\x0e$\xf7\xb6\xcb\xa5\xdb\x0e\xdeZV\xcf\xd2\xd5\x8f\xb6~\xdb\xf1\'{[\xd6xF/\\\x80\xb8l\x85\x9a\xc0\xf9qq\x97\xae\x00(\xb1.\x86\x82\x89ji-\x93\x05\x13\xa9\xa2WbR\x84\xc8\x9f*\x11\xa8\xa4\xb0\xbc` \x95\xd1X\xdbK\xaa\x14\x89c\xf5\x03\xa7\xd6\xc0\xb74\xb5G\xc0\xc9V$\x02\xd6U\xea\xf47\x90\xb1mq\xd34\xf7\x0b\xc2Lc\xd6\xf9y\xa0c\xdb\x02g\xe0c\xcb\ng\xac\xbb\xb4\xc4\xf9\x11\xa7\xc4\xcc8\xca\x86\x8f&\x9e\xac\xb3L\xee\x08(\xaf\xee"\xa2\xba\xce\x19}bH\t\xa4\x0fd\x00d\x18\x91\x86\xb8`\x04\xf71\x90\t\x90)\x90\x19\x909\x90\x05\x90%\x90\x15\x905\x90M\xe9\x86\xb6\xc6\xa8\xbb4\xc6\x88m\x1ac\xc5>\x8d\xb7\xbe#\x83\xb7\\\xaat\xb6\xed\x88\xe6\x9f\x80\x9c\x81\\\x808\x95\xd3\xaa\x9d\xca\x01\xea\x11"G*\x92\xa4J,\

In [4]:
raw1 = pd.read_excel('Análisis_de_Piso.xlsx', header=None)
raw1.head(5)

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
0,NaN,Leads Piso 2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,979,811,NaN,NaN,Factor minimo mejor vendedor,Factor minimo mejor vendedor,NaN,NaN
1,NaN,459,27,95,110,65,107,88,59,40,...,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
2,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABIGAIL,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0,1,5,1,0,1.00,5.00,1,20
4,ALAN GONZALES,1,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,6,0.61,59,40,0.31,0.02,3.28,2.22,7,10

Este reporte no tiene un encabezado simple de una fila: la fila 0 trae las categorías (Leads Piso 2024, Ventas Piso 2025, etc.), la fila 1 son totales por mes, y la fila 2 trae los nombres de los meses. Los datos de cada asesor empiezan hasta la fila 3. Por eso lo cargamos primero "en crudo" (header=None) para reconstruir la tabla correctamente.

In [5]:
meses_leads2024 = ['feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic']
meses_leads2025 = ['ene','feb','mar','abr']
meses_ventas2024 = ['feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic']
meses_ventas2025 = ['ene','feb','mar','abr','may','junio']

columnas_piso = ['Asesor']
columnas_piso += [f'Leads_2024_{m}' for m in meses_leads2024]
columnas_piso += [f'Leads_2025_{m}' for m in meses_leads2025]
columnas_piso += ['Total_Leads','Total_Leads_Ajustado','Raking_Leads','Raking_Leads_Ajustado']
columnas_piso += [f'Ventas_2024_{m}' for m in meses_ventas2024]
columnas_piso += [f'Ventas_2025_{m}' for m in meses_ventas2025]
columnas_piso += ['Leads_Prom_X_Mes','T_Ventas_Piso','Factor','Total_Ventas_Historicas','Raking_Ventas',
                  'Dependencia_de_Piso','Historico_PDM','Historico_SDC','Conversion_PDM','Conversion_SDC',
                  'Factor_PDM','Factor_SDC','Raking_PDM','Raking_SDC']

len(columnas_piso)

51

Se arman los nombres de columna combinando la categoría (fila 0) con el mes correspondiente (fila 2), leyendo directamente la estructura del reporte de Excel. Esto reemplaza el encabezado automático de pandas, que no puede interpretar celdas combinadas.

In [6]:
data1 = raw1.iloc[3:].copy()
data1.columns = columnas_piso
data1 = data1.reset_index(drop=True)
data1.head()

,Asesor,Leads_2024_feb,Leads_2024_mar,Leads_2024_abr,Leads_2024_may,Leads_2024_jun,Leads_2024_jul,Leads_2024_ago,Leads_2024_sep,Leads_2024_oct,...,Raking_Ventas,Dependencia_de_Piso,Historico_PDM,Historico_SDC,Conversion_PDM,Conversion_SDC,Factor_PDM,Factor_SDC,Raking_PDM,Raking_SDC
0,ABIGAIL,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0,1,5,1,0,1.00,5.00,1,20
1,ALAN GONZALES,1,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,6,0.61,59,40,0.31,0.02,3.28,2.22,7,10
2,ALICIA LEDESMA,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,1,0,0,0.00,0.00,NaN,NaN
3,AURELIO FELIPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6,...,11,0.38,28,31,0.29,0.01,3.50,3.88,9,18
4,CARLOS ALBERTO NIETO,NaN,NaN,NaN,2,NaN,NaN,2,8,4,...,8,0.6,64,30,0.23,0.02,4.27,2.00,13,7

Se descartan las primeras 3 filas (categorías, totales y nombres de mes) porque no son datos de un asesor, y se asignan los nombres de columna reconstruidos en el chunk anterior.

In [7]:
data1 = data1.replace(r'^\s*$', np.nan, regex=True)

/tmp/ipykernel_2233/2925538815.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data1 = data1.replace(r'^\s*$', np.nan, regex=True)

Varias celdas "vacías" del Excel original en realidad tienen un espacio en blanco oculto (carácter \xa0) en vez de estar realmente vacías, así que pandas no las detecta como nulas con isnull(). Esta línea convierte cualquier celda que solo tenga espacios en blanco a un NaN real, para poder identificarlas y tratarlas correctamente.

In [8]:
valores_nulos = data1.isnull().sum()
valores_nulos

Asesor                      0
Leads_2024_feb             19
Leads_2024_mar             31
Leads_2024_abr             23
Leads_2024_may             28
Leads_2024_jun             30
Leads_2024_jul             29
Leads_2024_ago             30
Leads_2024_sep             28
Leads_2024_oct             31
Leads_2024_nov             25
Leads_2024_dic             31
Leads_2025_ene             30
Leads_2025_feb             30
Leads_2025_mar             33
Leads_2025_abr             31
Total_Leads                 0
Total_Leads_Ajustado        0
Raking_Leads                0
Raking_Leads_Ajustado       0
Ventas_2024_feb            34
Ventas_2024_mar            38
Ventas_2024_abr            35
Ventas_2024_may            39
Ventas_2024_jun            38
Ventas_2024_jul            36
Ventas_2024_ago            36
Ventas_2024_sep            35
Ventas_2024_oct            38
Ventas_2024_nov            34
Ventas_2024_dic            34
Ventas_2025_ene            35
Ventas_2025_feb            33
Ventas_2025_mar            35
Ventas_2025_abr            37
Ventas_2025_may            34
Ventas_2025_junio          38
Leads_Prom_X_Mes            0
T_Ventas_Piso               0
Factor                      0
Total_Ventas_Historicas    14
Raking_Ventas               0
Dependencia_de_Piso         0
Historico_PDM               0
Historico_SDC               1
Conversion_PDM              2
Conversion_SDC              1
Factor_PDM                  0
Factor_SDC                  0
Raking_PDM                 17
Raking_SDC                 14
dtype: int64

In [9]:
valores_nulos = data1.isnull().sum().sum()
valores_nulos

np.int64(1087)

In [10]:
data1_limpio = data1.copy()

In [11]:
columnas_numericas = [c for c in data1_limpio.columns if c != 'Asesor']
data1_limpio[columnas_numericas] = data1_limpio[columnas_numericas].fillna(0)

Técnica: sustitución por un valor en concreto (0). Se aplicó a todas las columnas numéricas (leads mensuales, ventas mensuales, y las métricas calculadas como Factor, Conversión y Raking) porque, en este reporte, una celda vacía significa que ese asesor no tuvo actividad ese mes o no generó el indicador correspondiente — no es un dato que falte por error de captura, así que sustituirlo con media, mediana o ffill/bfill inventaría actividad que nunca ocurrió. La única columna sin tratar es "Asesor" (texto), que no tiene valores nulos.

In [12]:
valores_nulos = data1_limpio.isnull().sum()
valores_nulos

Asesor                     0
Leads_2024_feb             0
Leads_2024_mar             0
Leads_2024_abr             0
Leads_2024_may             0
Leads_2024_jun             0
Leads_2024_jul             0
Leads_2024_ago             0
Leads_2024_sep             0
Leads_2024_oct             0
Leads_2024_nov             0
Leads_2024_dic             0
Leads_2025_ene             0
Leads_2025_feb             0
Leads_2025_mar             0
Leads_2025_abr             0
Total_Leads                0
Total_Leads_Ajustado       0
Raking_Leads               0
Raking_Leads_Ajustado      0
Ventas_2024_feb            0
Ventas_2024_mar            0
Ventas_2024_abr            0
Ventas_2024_may            0
Ventas_2024_jun            0
Ventas_2024_jul            0
Ventas_2024_ago            0
Ventas_2024_sep            0
Ventas_2024_oct            0
Ventas_2024_nov            0
Ventas_2024_dic            0
Ventas_2025_ene            0
Ventas_2025_feb            0
Ventas_2025_mar            0
Ventas_2025_abr            0
Ventas_2025_may            0
Ventas_2025_junio          0
Leads_Prom_X_Mes           0
T_Ventas_Piso              0
Factor                     0
Total_Ventas_Historicas    0
Raking_Ventas              0
Dependencia_de_Piso        0
Historico_PDM              0
Historico_SDC              0
Conversion_PDM             0
Conversion_SDC             0
Factor_PDM                 0
Factor_SDC                 0
Raking_PDM                 0
Raking_SDC                 0
dtype: int64

In [13]:
valores_nulos = data1_limpio.isnull().sum().sum()
valores_nulos

np.int64(0)

In [14]:
data1_limpio.to_csv("analisis_piso_sin_nulos.csv", index=False)

In [15]:
from google.colab import files
files.download("analisis_piso_sin_nulos.csv")

In [16]:
files.upload()

Saving Ventas_por_Asesor.xlsx to Ventas_por_Asesor.xlsx

{'Ventas_por_Asesor.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00e1q\xc8\xaf\x01\x00\x00\xcb\x06\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x95MN\xc30\x10\x85\xf7H\xdc!\xf2\x16%nY \x84\x9av\xd1\xc2\x12\x90\x80\x03\x18g\xdaD\xf5\x9f<\xa6\xa4\xb7g\xe26\x15\xa0\xd0\x145\x9bXq<\xef{\x1eO\xc6\x93Y\xadU\xb2\x01\x8f\x9559\x1bg#\x96\x80\x91\xb6\xa8\xcc*go\xaf\x0f\xe9-K0\x08S\x08e\r\xe4l\x0b\xc8f\xd3\xcb\x8b\xc9\xeb\xd6\x01&\x14m0ge\x08\xee\x8es\x94%h\x81\x99u`\xe8\xcb\xd2z-\x02\xbd\xfa\x15wB\xae\xc5\n\xf8\xf5ht\xc3\xa55\x01LHC\xa3\xc1\xa6\x93\x05,\xc5\x87\n\xc9}M\xd3;\'\x1e\x14\xb2d\xbe[\xd8\xb0r&\x9cS\x95\x14\x81\x9c\xf2\x8d)~Q\xd2=!\xa3\xc8\xb8\x06\xcb\xca\xe1\x15\xd9`\xbc\x93\xb0\xa1/\xff\x02\xd8\xe5\xb2\x92PX\xf9\xa1\xc9|F\xf1\x0b/>)Q\x7f\x00\x1a\xf4\xdf\x80\xbd\xb1\'\xca\xbd\xaf\nH\x9e\x85\x0f\x8fB\xd3>y\xad\xf8\xa7\xf5\xebwk\xd7\xd9q\x91\x8e4\xfcr\x89\xce\x83(\xb0\x04\x08Zeq\xcc\xb4\xa8L\x9b\x98#\xfc\xb8\x18y\x1c\xc6\x03\x1bi\xf6\x17\x85{|\x04*(\xe0\xf1y\xbe\x85(\xd3\x03\xc4\xb0U\x80C\xa7=\x8a\xf6\x91K\xe1\xa1x\t\x9e*jp\x03\xdf\xb5{|H\xab\x9b\xfa\xc6\xa1\x8f\xbc\xd5\xed=\xf1\xa6`\xa1\x98\xefm\xd0\xe1\xff\x988\xc5\x96\xc6\x14j\t*kcOd;\xea\x83\xd6 \xdf\x8d\'\x14\xc1\x01\xb4\x8b\xe8\xcb\xacPr^\xd2\xcf7py\xc9V\xf7\x18\x9f\xfa\xd6\xb3\xb7\x0e\xa9\xf9z\xf8\xbf\x81\xb6\xbb6\xd1\xa9#!\xf0\xa1\x82C\x7f\xedj#\x07"5\xee\xb3w\x0c\xcd\xd5@e\xd1\xc1\xe6\xf1*\x9a~\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xb5U0#\xf4\x00\x00\x00L\x02\x00\x00\x0b\x00\x08\x02_rels/.rels \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92MO\xc30\x0c\x86\xefH\xfc\x87\xc8\xf7\xd5\xdd\x90\x10BKwAH\xbb!T~\x80I\xdc\x0f\xb5\x8d\xa3$\x1b\xdd\xbf\'\x1c\x10T\x1a\x83\x03G\x7f\xbd~\xfc\xca\xdb\xdd<\x8d\xea\xc8!\xf6\xe24\xac\x8b\x12\x14;#\xb6w\xad\x86\x97\xfaqu\x07*&r\x96Fq\xac\xe1\xc4\x11v\xd5\xf5\xd5\xf6\x99GJy(v\xbd\x8f*\xab\xb8\xa8\xa1K\xc9\xdf#F\xd3\xf1D\xb1\x10\xcf.W\x1a\t\x13\xa5\x1c\x86\x16=\x99\x81Z\xc6MY\xdeb\xf8\xae\x01\xd5BS\xed\xad\x86\xb0\xb77\xa0\xea\x93\xcf\x9b\x7f\xd7\x96\xa6\xe9\r?\x889L\xec\xd2\x99\x15\xc8sbg\xd9\xae|\xc8l!\xf5\xf9\x1aUSh9i\xb0b\x9er:"y_dl\xc0\xf3D\x9b\xbf\x13\xfd|-N\x9c\xc8R"4\x12\xf82\xcfG\xc7%\xa0\xf5\x7fZ\xb44\xf1\xcb\x9dy\xc47\t\xc3\xab\xc8\xf0\xc9\x82\x8b\x1f\xa8\xde\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00wW/\x9c\xc5\x03\x00\x00+\t\x00\x00\x0f\x00\x00\x00xl/workbook.xml\xacUmn\xe36\x10\xfd_\xa0w \xf4_\x91\xa8/KB\x9c\x85eI\xd8\x00\xf1n\xe0x\x93\x160\x100\x12\x1d\xb3\x91D\x97\xa4b\xa7\xc1\x1e\xa9\xa7\xd8\x8b\xedP\xb6\x9cd]\x14n\xb6\x81C\x8a\xe4\xf0\xf1\xcd\xcc\x1b\xf2\xf4\xc3\xa6\xae\xd0#\x15\x92\xf1fh\xe0\x13\xdb@\xb4)x\xc9\x9a\xfb\xa1\xf1e\x96\x9b\xa1\x81\xa4"MI*\xde\xd0\xa1\xf1D\xa5\xf1\xe1\xec\xd7_N\xd7\\<\xdcq\xfe\x80\x00\xa0\x91Cc\xa9\xd4*\xb6,Y,iM\xe4\t_\xd1\x06V\x16\\\xd4D\xc1P\xdc[r%()\xe5\x92RUW\x96c\xdb\x81U\x13\xd6\x18[\x84X\x1c\x83\xc1\x17\x0bV\xd0\x94\x17mM\x1b\xb5\x05\x11\xb4"\n\xe8\xcb%[\xc9\x1e\xad.\x8e\x81\xab\x89xhWf\xc1\xeb\x15@\xdc\xb1\x8a\xa9\xa7\x0e\xd4@u\x11\x9f\xdf7\\\x90\xbb\n\xdc\xde`\x1fm\x04\xfc\x02\xf8\xc764N\x7f\x12,\x1d\x1cU\xb3Bp\xc9\x17\xea\x04\xa0\xad-\xe9\x03\xff\xb1ma\xfc&\x04\x9b\xc3\x18\x1c\x87\xe4Y\x82>2\x9d\xc3=+\x11\xbc\x93U\xb0\xc7\n^\xc0\xb0\xfd\xd3h\x18\xa4\xd5i%\x86\xe0\xbd\x13\xcd\xdfss\x8c\xb3\xd3\x05\xab\xe8\xf5V\xba\x88\xacV\x9fH\xad3U\x19\xa8"Re%S\xb4\x1c\x1a\x03\x18\xf25}3!\xdaU\xd2\xb2\nV\x9d\x00\xbb\xb6a\x9d\xed\xe5|)PI\x17\xa4\xad\xd4\x0c\x84\xdc\xc3Ce\x04A\xe4\xf8\xda\x12\x841\xaa\x14\x15\rQt\xcc\x1b\x05:\xdc\xf9\xf5\xb3\x9a\xeb\xb0\xc7K\x0e\nGS\xfag\xcb\x04\x85\xc2\x02}\x81\xaf\xd0\x92"&w\xf2\x92\xa8%jE54\xc6\xf1\xfc\x8b\x04\xf7\xe7\xa4Z\x08:\xff\xdc\xd0T\xb0G:\xef\xab\x83\xcb\xf9\x8c\x16\xe0\x0e\x9ah\x9aB\xd0\xa7\xb9c;\x01\xba\x02\xc7\xa4\x12\x14%\xb73*\n\xc6\xd1-\x9e_B\x11\x91\xae\\\xa5\xdeB\x1aR}\xfb[\xb1\x82\xe8QC\xef9\xd8I\xb4"\x82 (f\xd2\xb0\xbf\x08\xcc4T\xce_\x15\x029\xac\xba\xffP\n\xa4\xd0\xf1\xb5 \xc0\xdb l\xbf\x7f\x0c6\xc4B\xc4\xbd\xdc/\x95@\xf0}\x9e^@\xca\xaf\xc8#\x08\x00dV\xee\xee\x87s\xc8px\xfb\xecy\x037\n\xa2\xc4L\xc7\x91kz^\xee\x98\xa3 \xca\xcc\x11\xce3g\x90z\xde8w\xbf\x82\x17"\x88\x0bNZ\xb5\xdc\x89Jc\x0e\r\x0f\x14t\xb04!\x9b~\x05\xdbq\xcb\xca\x97\xf3\x9f\xed\xdd\x9f\xa9\xfb\x1f\x9a~\xed\xab\xf6T_\x9f\xd7\x8c\xae\xe5\x8b\xfc\xf4\x10mnXS\xf2\xf5\xd00\xb1\x03\xde<\xbd\x1d\xae\xbb\xc5\x1bV\xaa%\xe8\xd7\x1e\x80~\xd1v\xee#e\xf7K`\x8c\xb1\xed\xe9b\x13\x8ef64\x9e\xc7\xa1\xed$!\xceM\xcf\xf5}\xd3\xcb\x06\xb6\x19\x8e\xdd\xc4\x0c<\xdf\xc3.N\xc3A\xe4t\x8c\xacW\x94\xba\x8b\x1a\xa8u=j\xba\xe2\xfa\xc8\xff \x18\x1e\x04}\x87\xeb\xe0\xc2\xb7\x88\xf5\x11\xe2\xbc\xc4]\xf2\xfa]\x05\xa9\n\xa8%\xddu\x86\x11\xb6\x9dH[\xd0\x8d\xba\x90\xaa\xebA\xc6\x0c\xd8a\xcf\x1e\r\xec\xc83\xed\xcc\x05va\xe4\x98\xa1\xe7:\xe6\xd8K\x9d\xcc\x1fdi\x96\xf8:=\xfa\x9d\x89\xff\x8f\xdb\xb6\xab\xa6\xb8\x7f\xc04\xcb%\x11j&H\xf1\x00\xcf\xde\x94.\x12"AH[\x87\x80\xefk\xb2\x89\x1f&\xb6\x0b\x14\xbd\\\xc7\x13G\xb6\x99$\x81g\xfai\xee\xfa\x03\x9c\x8e3?\x7f!\xab\xdd_\xbc\xf3\xae\x0b\xadn7%\xaa\x85{@_\x01\xdd8\xd6m\xbe\x9b\xddO.\xb6\x13\xbb4\xbd\xa9\xb9x\x9a\xea\xb8\xefv\xff\x9b\xe1\x15x_\xd1#\x8d\xf3\xeb#\r\xc7\x9f&\xb3\xc9\x91\xb6\x17\xd9\xec\xf6&?\xd6x4I\xd2\xd1\xf1\xf6\xa3\xe9t\xf4\xfb,\xfb\xad?\xc2\xfa\xc7\x80Z]\xc2u\xdb\xc9\xd4\xeaer\xf6\x1d\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00E\xe2\xc1I\'\x01\x00\x00\xbc\x03\x00\x00\x1a\x00\x08\x01xl/_rels/workbook.xml.rels \xa2\x04\x01(\xa0\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x93\xcbN\xc30\x10E\xf7H\xfc\x83\xe5=\x99\xa4@A\xa8I\x17 \xa4n!|\x80\xe5L\x1ej\xfc\x90\xc7<\xf2\xf7X\t4\x89T\xc2&\x1bK3#\xdf{<\xba\xde\xed\xbfT\xcb>\xd0Qct\xca\x93(\xe6\x0c\xb54E\xa3\xab\x94\xbf\xe5\xcfW\xf7\x9c\x91\x17\xba\x10\xad\xd1\x98\xf2\x0e\x89\xef\xb3\xcb\x8b\xdd\x0b\xb6\xc2\x87KT7\x96XP\xd1\x94\xf2\xda{\xfb\x00@\xb2F%(2\x16u\x98\x94\xc6)\xe1C\xe9*\xb0B\x1eE\x85\xb0\x89\xe3-\xb8\xa9\x06\xcff\x9a\xecP\xa4\xdc\x1d\x8ak\xce\xf2\xce\x06\xe7\xff\xb5MY6\x12\x9f\x8c|W\xa8\xfd\x19\x0b \xdf\xb5\xe1\x01,\x17\xaeB\x9f\xf2\xa1\x8e\x02#\x87\xf3\xf6\x9b5\xed}X\x0b\x8e\xee}\t\xfd\x99,1$k2|\x1aw\xa4\x1a\xd1\x8f\x1c\xa7\x16A?Y\x84\xd9\xae\t#E+\x1fk\xd1\xe8\x11\xe6\xd4Z\xda\xc8\xed\x1f\x10\xaa\x91\xce\x90)}$\x8d\x82!\x0f!\x07\xc9\x1d$\xf1<m`C\xe6\xcd\xc4w\xa8\xe9\xa7\xbfd~\xb3j"k\xe1\xb0x\xf5.|\xb8i0\xa7\xed_\x18\x98\xfd\xb9\xec\x1b\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00R\xc9\x81B\t\'\x00\x00\x8b\x12\x01\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\x9c\x93M\x8f\x9b0\x10\x86\xef\x95\xfa\x1f,\xdf\x89\x81@\xc2"\xc8*\nB\xddC\xa5\xaa\xdb\x8f\xb3c\x0f\xc1\n\xc6\xd4v6\x89\xaa\xfe\xf7\x1a\xa2\x90\xb4\xb9\xa0\x95\x8cd\xfc\xf1\xcc\xfb\x8eg\xb2\xe7\x93l\xd0\x1bh#T\x9b\xe3`\xe6c\x04-S\\\xb4\xbb\x1c\x7f\xffVz\tF\xc6\xd2\x96\xd3F\xb5\x90\xe33\x18\xfc\xbc\xfa\xf8!;*\xbd75\x80E\x8e\xd0\x9a\x1c\xd7\xd6v)!\x86\xd5 \xa9\x99\xa9\x0eZ\xb7S)-\xa9u\xbfzGL\xa7\x81\xf2\xe1\x92lH\xe8\xfb\x0b"\xa9h\xf1\x85\x90\xea)\x0cUU\x82A\xa1\xd8ABk/\x10\r\r\xb5N\xbf\xa9Eg\xae\xb4\x13\x9f\xc4\xe3\x9a\x1e\x9d\xd7\xab\x9e;\x89\xc5eg\xe4\x05\xd1\x83>)\x98VFUv\xc6\x94$\x17i\x8f.\x9f\xc8\xd3?>%\x9bbTR\xbd?t\x9e\x03w\xce\xdcV4\xc2\x9e\x07\xbb\x18I\x96\xbe\xecZ\xa5\xe9\xb6q/r\n"\xca\xd0I\xbb\x11\xbao~\'\x98>F\x9a.\x99\xb2\x91\xf4\x98\xc9I\x98 "\x1a\xdeD_Z7T\xf8\xbe,\x06\xf1\xc8\no\xb0\xf9;a\x8b\x11\xd6\xa7K\xa7\x07\xc1s\xfc;\x89\xfd\xa8\x0c\xfc\xd2+6\xe1\xda\x8b\x8a\xa2\xf0\x92h\x13z\xebd\xbe\\\xfa\x9b2\\$\xcb?x\x95q\xe1j\xafw\x854T9^\x07\xe9\xfas\x1cc\xb2\xca\x86\xda\xfe!\xe0h\xee\xe6\xc8\xd2\xed+4\xc0,\xb8(\x01F}\xebl\x95\xda\xf7\x07_\xdc\x92\xef\x98f8\xd03\xcd\xaf\xff\xa9d\xc4\xae\xb2\xdb\xfc\x1a\xa2\x1c:\xec\x8bF[j`\xa3\x9a\x9f\x82\xdb\xda\xc5q\x9d\xcc\xa1\xa2\x87\xc6~U\xc7O v\xb5u\xab\xb1\xf3\xdb\x17L\xca\xcf\x05\x18\xe6z\xc8\xc5\x9f\x85\xbd\xfa\xbf\x00\x00\x00\xff\xff\x00\x00\x00\xff\xff\x9c]]\x8f\xe3\xb6\x92\xfd+Ao\x1er\x81\xe0\xce\xb8\xdb\xee\x99id\x06\x90\xdb\xb2eY\xf2G\xb7\xdd\xfex\x0br\'\xc8}\xd9]d\x82\xec\xee\xbf_R"E\xb1N\xa9T\x9c\x87|\xe0\xf0T\x91\xb2\xc8\xa3"U\xa5\xfe\xe5\xdb\x1f_\xbf\xfe\xb5\xf8\xf5\xaf_\xbf\xfc\xf2\xe7\x7f\xfd\xcf\x0f\x7f~\xbe\x9b\xdc\xfd\xf0\xed\xbf\x7f\xfd\xcfo\xe6\xff\x9e\x1e>\xdd\xfd\xf0\xbf\x93\xe9\xaf\xbf=\xfd\xeb\xff\x16_\xbf\xfd\xf6\xf5?\xff\xfa|\xf7\xfe\x9f\xf7\xb3\xbb/\xbf\xfcf\xc9\x99e76\xa6\xe1\x9bA\xff\xfe\xf2\xfe\x97w\x7f\x7f\xf9\xe5\xddo\x8e1o\x19\xf7\xa6\xed\xf7\x1f,\xe9\x8f_\xff\xfc\xfa\xaf\xbb\x1f\xfe\xfc\xfa\xfb\xe7\xbb\xf9\xe4\xe9`\xdb\xffm\xbc\xde}y=\xd5?\xcd\xa7O\xf3\xd9\xe4\x1f\xbf\xbc\xfb\xdd\xfa\x9a\xdc\xc7\xce\x9e\x07\x9c\xb5\x0e\xdeY\x93\x0f\xb1\xc5b\xdc\xe2cl\x91\x8f[L\x1eb\x93\xe5\xb8\xc9cl\xb1\x1a\xb7\xb8\x9f\xc4&\x85b\\\xe4\xe2\xd7\xe9&\xa5b`\xe4\xea7\n\x13r\x1f\xabq\x93\x07bR+z!?\xf2VaBf\xebN10b\xb2O7i\xe6\xfc\xe7;X\x13\xbdi\xfc0\x8d\xef\xfe\x8b\xb4\x8c^&O7\xb7\x8c&\xed2z\x99>\xbd\x84e4%C~\x15\x86<\xb9k\x96\xd1\x03\xf9-\x8f\xad\xc9\x03]\xc6v\xc8\xce\xe4\x9e\xcc\xbeSk2\x15L\x1e\xc8\xda{\x1b7\xa1\xd7rV\x98\x90\xa9tQ\x0c\x8c\xfc\xfc\xd7\xf4ki\xee\xc8\xe7;\xf1\xf2I/\x99\x93\xd3\xc6\xa6\x91\xc3,\x9b>e\xd9l\xea\x05qJD!s\xf2j\x05\xf9\xf7\xd6\xc2(h6\x17,\x9c\x86\xf6\xfax6\x16\xcf\xc1\xe2a\x16O\xbd\xccih\xcfba,\x16=\x0br\xe73\xa7\xa1=\x8b\xdcX\xe4\xc1bBfd\xe6$\xf4\xd1\xce\xbe\xf6\xc9\xe2$\xf2C@\x8c\x02vWY\x18\x7fE\xcf\xdf\x072\x932#d\x1d\xb94\xe4\xb27\xdcOt\xbcF\x8f:re\xc8U \xdf\xf7V\xc2;\xf3\x88\xec\x9e\x93\xf7I\xcfI\xcb\xfe|\xf7\xb1\xbb\x98y\x0b|j\x1e\x99\xd3\xd9\xc3=\x11\xd5g\xd2>#sxA\xda?\x12\xfb<n\x9f\xc2#\x8b\xb4O\xc9T\\\x91\xf6\x0f\xa4\xbd\x88\xdbg\xef\xc9\xa4Y\x93v\xaa\'%i\x7f$z\xb3!\xed\xf4\x96Uq\xfb#\x15\x9f\x9a\xb4\xcf\xc8\xfc\xd8\x92\xf6\x8f\x9f\xe2I\xbf\x8b\xdb?L\xc8\x94\xd9\x93\xf6)\xf1\x7f \xedt~\xbe\xc4\xed\x1f\xdf\x93\xfe_I\xfb\x03i?\x92\xf6\x0fdA\x9d\xe2\xf6O\xef\x89p\xbc\x91\xf6\x07\xd2~&\xed\x8fTCI\xfb\'\xd2~\x8d\xda\x1f\xdf\xd3\xf9}#\xed3\x90BB\xf8H:\xc8\xdc\n\x9a\x98\xc0\xd1\x84}\xd3\xc7\t\x9d\xe2\x99[C\x811%\x8b$s\xab(0\xe84\xcf\xdc:\xea\x18\xf7\xef\xe9@\xddJ\xe9\xebT;\xf4\x89\x15\x95\xbf\xbf\xdc\xbf\xbf\xa7&nq\x18B\xa7vn=LlL\xd0\xd8P\x11v\x0b\xa2o\xe3\xd6@\xb0!k(s\x8b\xa0\xb5\x89\xc4\xeb\x81\x88\xd7\x1f&2\x9f|\xfc\xe7\x87\xd9X\xbco\r\r\xd5\xfc\xa7\x0b\xf8\xc9\xcc\x99;\x8a\x15\x7f\xee\xea\x9f\xbbv\x7f\xf1\x0b@r@\x96\x80\xac\x00)\x00Y\x03R\x02\xb2\x01\xa4r\xc8\xac\xbb=5\xbd&rw\xb6\xe0c\x07\xc8\x1e\x90\x03 /\x80\xbc\x02r\x04\xe4\x04\xc8\x1b g@.p\x95W\x87<\xfa;G\xe6\xd3\xadk\xef\xa6m\x86\x90\xbf\xff\xbdG\xb9\xbf\xe5=\xc8\xdf\xf3\xde\xb2\xf17\xbd\x07\xf9\xbb\xfe\xb1{<\xdb\xe8\xa6\x17G|\x9c\xd0\x80\xc8M\x8b\x0f\xbd\tJ\x95\xc3\xce\x93n\xf6RI\xb0S\xa6k\xa4\x0b\xd7\xce\x9eAK;\x91\x06-\xed\x9c\xea\x1a\xe9\xda\xb6\xd3\x8b\xb1\x8cV\xec4)\xdc\xb0l\xb2L\xc9\xcd\x9c;\x8a\xd9\xe1w]\x93g\xdc\xf38e\xd1Q\x9a\xed:\xd9IG\x8d\xe4.,\xc7\x9d\xaf"{2\xb8Br\xbe\x8e\x1a\xc9-.\xa5\xc6\x8dtA\x95dYG\x8dt+*Y\xee\xa4\xc6\xbd\xf4#\x1c\xda\xc6\xfb\xf6\x19H\xae\xf3%\xb2$s\xeeU\xea\xf3(\xfd\xb6\xa7\xa8O\xe2\xf6-\xb2$\xcb\xe7,\x8d\xf6\x125\x92U}\x95~\xdb\x9b4Z\xb3\x81j\x97B\x1biC\x10!]L\xe6\x16\x80\xfby\xa9\xad\x9b\xfb\xf7\xedc\x9eJE\xee<\xf7\x9e\xf1n\xca\xdf7\xfb~\x7f\xda\x95\xe5\xdd\xe6\xee#\xdd\xc3\xb8\x05\xd0j\xd9\xd7F\x03_\xb2\xed\xe6\xa7l9\xfd\xf9\xc7l\xf9\xe3\xe3\x93\xfd\xf7\xec\xf1\xe7\xf7~\x7f\xf8\x1f\xdbw\x19\xd9\xbd\x99\x85\xe2\xf76F<\xab\xae\xb7{z=v\xd1\x18)\xe8\xf7S\xd8~\x8a\xa6\x9fb\xac\x1f\xb3\xac|?\xf5\xf4\xe9\x12\xb6\xac\x10\xc9\xb4\xc4\xf6JJ\xdbC\xd9\xf4PF=\xd0\xd1\x99\xb5\xe7\xdd_\xed3 \\\x07}\x02\xd8\x85H\xae\xa3\xb2\xbdTM/\xd5\xf0uDzk"\xa1\x84cP\xcb6\x07:}\x1d\'7s\xee(\xe6 aPo\xc7)\x8bqJ>NYv\x14F\xb5WRc\x115\x12\xc1Y\x8f\xf7\\F\xf6\xe4\x1eo\xa4\x9e+\xa9\xe7Zr\xbb\x95\xdc\xee\xa2F\xba\xc9\x93\xfa<\xb8\xc66\xce%\xdb\xb3\x97\xc8\x92j\xaf\xd4x\x94F{\x8a\xfa$?\xff\x9bt)\xe7\xc8\x92\x88\xd5Ej\xbcJ\xa3\xbdI\x8d\xe6\xe0\xaa]\x16\xbcB\xfa\x15\xe16\nD\xb6\x9e\xa31\xc1\x91\x94tgL\x80\xd8\xef\x97*\x89\x9f\xfd\xfc+\x89l9{2\xffX\xf56G\x9b\x86\xd3\xbc\x950X>\xf3"\x8b:\xdd\xf6\xd7\xd3ix\xd3\x91\xad\x8c\x8b\x95wk\x8eQ\x9d\x90\xcf\x12\x84\xbc9\xe4C\xcf\x85\xf1l\x8e\xc2\xda\x01\x9b\x1f\xd3\r\xb8\xea\xc6\x0b1\xb2]\xa8^!\xd1\xdf\xda\xf8[{\x7f\xa6\xcfv\xa4\x85\x1d\xa9\xf6Q00\xd2\xd2x6\xe7p\xedH\xcd.\xc3\x8e\xb4\x9e=]\xba\x91\xce\xa8\x96[I Z^\xda\x81pO\x0c\xe6\xd9gD\x83{\xedd\xce\xf7\x9a3\xbev \x1f\xda\x81\\\xa3{|\x0f{i\x1cIeG\x92\xf6TyLz\xaaX6y\xaa\x10\x9d\x99;\x8a\xf4T\x19\xa7,\xc6)yGa\x1e\x19\xcb\xa8\x91\xac\xb7U\xd4H\xa3\xf8\xa8\x91\x9e!JnK\xa9q\x135\x12\xb5\xab\xa4\xc6Z\xba\xce\xed\xf8\xef\xb4\x1b\xa7\xec\xc7)\x07Gi#\x99\xf6\xbd*\xf9\xe5^:/~3\xfe\n\xc8\x11\x90\x93C\xc2\xd1\xc6\x1bp\xce]\xe7\xde\xf3\x05\x90+X\xdd\x00\xc92\x84\xfc|\x9d\x86\x93\xafgp\x9e\x85\xf9\xd8\x1d4\x84\xf9\xd7A~\xd6\xb1\xaf\xd1\xee\xdb\xd7X\xf7\x10R\xb7\xbd\x995\x1f\xbf\x8e\xb6b\xff\xd0\xda\xd0\x95_\xd8\xf3\x90\xe8\xdd\xb5%7W`\xce\xb7\xe8\xab\x84u\xc3\xf6\xa2\xf98 \x9aT\xe7\xcclf\xfah\xceK\xcc[p\xf2h4\xb3\x9bU\xb5\xcd\xe3S\xb6\xf1\xf2j\x8eL\\\x84m\xc7\xc0F\xd8\xf4\xa1j\x16\x063\x88\xe68\x06^\xebgf\xa1\xb0\x83\xa8\xcd j?\x08\xb3\xe9j\x07Q\xd9ApR\xd9;W\x8f\xc2o\xf3,M\x08\xbf-\x9b\x08%}\xc34w\x9c6\x16!?\xe9s\xd78\x18\x9c/\xc6)y\xd4\x05=\xef\x18\xb7_\x8dS\x8aq\xca:\x1a\x05=\xfb\x90\x86\xb8\x91~\xa2Jj\xac\xa5\xc6\xad4\xa0]\xd4H\x96\xde^r{p\x8dm\xf8H\xcf>\xa4\xeb|\x8d\x1a\xc9*8Fn\xc9M<\xb9\xc6\xf6\x84\x94\xbeRq\x8dV[\xcc\x0b\x89x\xd1\x9e#K2\xdaK\xd4H_=\xbbF{\x06j\xb4\x80tz\x93:\xcd\xb2\xa8\x95f\xd3d~M\xb8\xcb\xa1\xefd\xfd\xaah\x9b\xa9,\xfa\x05\xd1^.\x89K2\xbf\x16\xdaV\xaa`K7.I\xba?\x81t\xb7F\x92t\xd3~\xccr\x19\x96nx\x07mV\x0e\xc3n\x1e\x95p?\xb3\x92%;\xc5\x86W\xe8fi1\xae\x9b\xd7\xc1\xe8\xda,\xb5a\x1d\x9e\xd1\x03k\xb3\xf6\xec\xc1\x88\xd3\xd9\x0fC:\xdbM\xc7Hf?&\xc9\xaceS\x99\xa5o\x7f\x1cG\nH;J\xf3\x82\x88\xe4kE\x8d\xf4\xa5v\xd4H\x16\xeeRr\xbb\x92\xdc\x16R\xe3Zj,\xa3F\xb2p7\xe3?E5N\xa9\xc7)\xdbq\xcan\x9c\xb2\x1f\xa7\x1c\x1cE\nK;/]X\n\xc8\x11\x90\x93C\xdewa\xe1\x1bp\xce]\xe7]X\n\xc8\x15\xacn\x80d\x19Bs\xf0\x94=#\xb4@\xc3\x1c!?\x0f\xc5\xb0\x94\x86^n~J\xdaF\xe5\xd0\xccZ!,\xa5\x1d\x98i<\xacm\xf4\x84\xc4L\xeb\xe1h\x94>%\xcc4\x1f\x96\xb6\x07\xca63>!\xc6d\xc9\x9f\xda0}(r4/\xb4\x12"G\xcb\xa6\x92F~\x8e\xb9\xe3H\x926NY\x8cS\xf2q\xcar\x9c\xb2\x1a\xa7\x14\xe3\x94\xf58\xa5\x1c\xa7l:\n#\xf5\x95\xd4XG\x8d\xf4u\xbbd\xb9\x8b\x1aiD)Y\x1e\\c\x1bQ\x92\x07\xdb\x8b4\xa0\xd7\xa8\x91<\xb5\x8eR\x9f\xa7\xa8Oz\xa2+\xb9=G\x964=Gj\xbcJno\xd2h\xb3,j\xa5\xe1\x96_)\xfd\xdd}7\x90n\xdf\x1eVB\xd8\xddwn\xc3\xee\xdeA\x92\x8cNiL\xea\xe6\xbe$\xa3\xf4=\x9dY\x0b\xc32\n\x89;,\xd9E\x88\x10O\x9a\x052,\xa34!.3kE\xd0Qr\x04`\xd6\xce\xb0\x8c\xc2\xd1%K\xf62\x1anb\x14\x19\x9a\x8c\xa7\xa4:\x00K\xa7BJ\xa6\xf3\xbc\xf1iH\x92\x92*8\x0b\x05\'Wp\x96\n\xceJ\xc1)\x14\x9c\xb5\x82S*8\x1b\x05\xa7Rpj\x05g\x1b8\xcc\xa1\xef.n%\xf7z\x1f\xb7\x92S\xb2\x83om\xa5\x96L\xd8\x97\xd8\x96\xbe=\x8b[\x89\xf0\x1d\xe3V\xb2\x80Oq\xbf4yA\xb4=\x8b\xb6\x17\xb1\xf5*z\xbe\x89\xbf\xa4I\nwk\xab=\xba\xa2\x91]\xb7\xaa\xd8\xc7V\xf6,\xfe\xd4&\xb7;rN7\x97\xbded\xa7\x00m\xeeV\x90\xa4\xd2\x1fhx\xe9\xd7\x94$\xd3\x90\xb3e\xc69\xac\xd34\xca\xb4\xabM\x08w!\xad\x8b\xa7\xbb\xcd\xfc\x94\x1e\xf1\xda58,\xd5\xf4\xa1hW\xe3\xb0V\xdfC.\x18Owj\x1d~\x96X\xacmyBB\xd1\x96\xab\xff\xe8\xa7+L\xc8\x8f27Y\xa3\x8d\xa2\

In [17]:
raw2 = pd.read_excel('Ventas_por_Asesor.xlsx', header=None)
raw2.head(5)

,0,1,2,3,4,5,6,7,8,9,...,29,30,31,32,33,34,35,36,37,38
0,Ventas X Mes,12,7,8,13,6,21,17,17,23,...,37,10,NaN,NaN,178,NaN,397,NaN,236,NaN
1,NaN,2024-02-01 00:00:00,2024-03-01 00:00:00,2024-04-01 00:00:00,2024-05-01 00:00:00,2024-06-01 00:00:00,2024-07-01 00:00:00,2024-08-01 00:00:00,2024-09-01 00:00:00,2024-10-01 00:00:00,...,2026-06-01 00:00:00,2026-07-01 00:00:00,NaN,NaN,2024,NaN,2025,NaN,2026,NaN
2,Nombre vendedor,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,811.0,Raking,Acum,Ranking,Acum,Ranking,Acum,Ranking
3,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4,NaN,88.0,NaN,22,NaN,45,2,21,NaN
4,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,3,2,88.0,NaN,11,NaN,51,NaN,26,NaN

Igual que con Análisis de Piso, este reporte trae varias filas de encabezado antes de los datos reales: la fila 1 tiene las fechas de cada mes (2024-02-01, 2024-03-01, etc.) y la fila 2 tiene la etiqueta "Nombre vendedor" y algunas columnas de resumen (Raking, Acum, Ranking). Los datos de cada vendedor empiezan hasta la fila 3, y la última fila del archivo es "Total general" (un renglón de totales, no un vendedor real), así que también hay que excluirla.

In [18]:
fechas = raw2.iloc[1, 1:31]
meses_cols = [f"Ventas_{d.strftime('%Y-%m')}" for d in fechas]

columnas_ventas = ['Nombre_Vendedor'] + meses_cols + ['Col_811', 'Raking',
                   'Acum_2024','Ranking_2024','Acum_2025','Ranking_2025','Acum_2026','Ranking_2026']

len(columnas_ventas)

39

A diferencia de Análisis de Piso (que usaba nombres de mes como texto), aquí la fila 1 ya trae fechas reales, así que se usan directamente para nombrar cada columna mensual (Ventas_2024-02, Ventas_2025-01, etc.). Las últimas 8 columnas son resumen: un valor sin etiqueta clara en el archivo original (Col_811), un raking general, y el acumulado/ranking de ventas por cada año (2024, 2025, 2026).

In [19]:
data2 = raw2.iloc[3:54].copy()
data2.columns = columnas_ventas
data2 = data2.reset_index(drop=True)
data2.head()

,Nombre_Vendedor,Ventas_2024-02,Ventas_2024-03,Ventas_2024-04,Ventas_2024-05,Ventas_2024-06,Ventas_2024-07,Ventas_2024-08,Ventas_2024-09,Ventas_2024-10,...,Ventas_2026-06,Ventas_2026-07,Col_811,Raking,Acum_2024,Ranking_2024,Acum_2025,Ranking_2025,Acum_2026,Ranking_2026
0,PEDRO GONZALEZ ESPINDOLA,,,1,2,,7,2,3,3,...,4,NaN,88.0,NaN,22,NaN,45,2,21,NaN
1,VICTOR MANUEL SANCHEZ ARRO,,,,,1,1,3,,2,...,3,2,88.0,NaN,11,NaN,51,NaN,26,NaN
2,MIGUEL ANGEL SONDEREGGER,,,,1,2,7,5,2,2,...,NaN,NaN,28.0,6,27,1,1,25,0,17
3,JOSE ANTONIO LICONA MENDE,1,,,2,,,,3,2,...,9,1,98.0,1,10,4,35,4,53,1
4,JAIME GONZALEZ CORONA,,2,3,5,2,3,3,3,4,...,NaN,NaN,25.0,8,25,2,0,30,0,17

Se toman solo las filas 3 a 53 (los 51 vendedores reales), dejando fuera las 3 filas de encabezado de arriba y la fila 54 ("Total general") que es un renglón de totales, no un vendedor.

In [20]:
data2 = data2.replace(r'^\s*$', np.nan, regex=True)

/tmp/ipykernel_2233/4006048100.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data2 = data2.replace(r'^\s*$', np.nan, regex=True)

In [21]:
valores_nulos = data2.isnull().sum()
valores_nulos

Nombre_Vendedor     0
Ventas_2024-02     46
Ventas_2024-03     47
Ventas_2024-04     47
Ventas_2024-05     45
Ventas_2024-06     47
Ventas_2024-07     45
Ventas_2024-08     46
Ventas_2024-09     44
Ventas_2024-10     41
Ventas_2024-11     39
Ventas_2024-12     39
Ventas_2025-01     38
Ventas_2025-02     40
Ventas_2025-03     44
Ventas_2025-04     40
Ventas_2025-05     42
Ventas_2025-06     38
Ventas_2025-07     39
Ventas_2025-08     40
Ventas_2025-09     37
Ventas_2025-10     37
Ventas_2025-11     39
Ventas_2025-12     38
Ventas_2026-01     40
Ventas_2026-02     37
Ventas_2026-03     37
Ventas_2026-04     37
Ventas_2026-05     40
Ventas_2026-06     38
Ventas_2026-07     44
Col_811             0
Raking              2
Acum_2024           0
Ranking_2024        2
Acum_2025           0
Ranking_2025        1
Acum_2026           0
Ranking_2026        2
dtype: int64

In [22]:
valores_nulos = data2.isnull().sum().sum()
valores_nulos

np.int64(1238)

In [23]:
data2_limpio = data2.copy()

In [24]:
columnas_numericas2 = [c for c in data2_limpio.columns if c != 'Nombre_Vendedor']
data2_limpio[columnas_numericas2] = data2_limpio[columnas_numericas2].fillna(0)

Técnica: sustitución por un valor en concreto (0), igual razonamiento que en Análisis de Piso. Una celda vacía en las ventas mensuales significa que ese vendedor no vendió nada ese mes, y las columnas de resumen (Raking, Acum y Ranking por año) se derivan de esas mismas ventas, así que su ausencia también corresponde a 0 actividad. La única columna sin tratar es "Nombre_Vendedor" (texto), que no tiene valores nulos.

In [25]:
valores_nulos = data2_limpio.isnull().sum()
valores_nulos

Nombre_Vendedor    0
Ventas_2024-02     0
Ventas_2024-03     0
Ventas_2024-04     0
Ventas_2024-05     0
Ventas_2024-06     0
Ventas_2024-07     0
Ventas_2024-08     0
Ventas_2024-09     0
Ventas_2024-10     0
Ventas_2024-11     0
Ventas_2024-12     0
Ventas_2025-01     0
Ventas_2025-02     0
Ventas_2025-03     0
Ventas_2025-04     0
Ventas_2025-05     0
Ventas_2025-06     0
Ventas_2025-07     0
Ventas_2025-08     0
Ventas_2025-09     0
Ventas_2025-10     0
Ventas_2025-11     0
Ventas_2025-12     0
Ventas_2026-01     0
Ventas_2026-02     0
Ventas_2026-03     0
Ventas_2026-04     0
Ventas_2026-05     0
Ventas_2026-06     0
Ventas_2026-07     0
Col_811            0
Raking             0
Acum_2024          0
Ranking_2024       0
Acum_2025          0
Ranking_2025       0
Acum_2026          0
Ranking_2026       0
dtype: int64

In [26]:
valores_nulos = data2_limpio.isnull().sum().sum()
valores_nulos

np.int64(0)

In [27]:
data2_limpio.to_csv("ventas_por_asesor_sin_nulos.csv", index=False)

In [28]:
files.download("ventas_por_asesor_sin_nulos.csv")